### ISSUE TITLE
Getting AWS error when opening Courier Inbox

### ISSUE THREAD

**Issue by colby-mchenry** [trycourier/courier-react-native#15]
For some reason, when I open the CourierInbox it throws errors. 

![IMG_947036FBC873-1](https://github.com/trycourier/courier-react-native/assets/140429921/75cf33b5-1afd-4180-87e6-2ab643b06877)

**My listener/setup for Courier, this is placed in the App.tsx and works just fine, Courier console logs the user logging in without a problem**
```
const ACCESS_TOKEN_MUTATION = gql`
  mutation GrantCourierAccessToken($userId: UUID!) {
    courierAuth(input: { userId: $userId }) {
      token
    }
  }
`;

export const CourierAuth = () => {
  const [getAccessToken] = useMutation(ACCESS_TOKEN_MUTATION);
  const userID = useSelector(userIDSelector);

  const signIn = async () => {
    if (userID) {
      try {
        const resp = await getAccessToken({
          variables: {
            userId: userID,
          },
        });
        await Courier.shared.signIn({
          accessToken: resp.data.courierAuth.token,
          clientKey: Env.COURIER_PUBLIC_KEY,
          userId: userID,
        });
      } catch (error) {
        Alert.alert('Could not connect to Courier.');
        console.error(error);
      }
    }
  };

  useEffect(() => {
    if (userID) {
      signIn();
    } else {
      Courier.shared.signOut();
    }
  }, [userID]);

  useEffect(() => {
    // Setup Push
    Courier.shared.iOSForegroundPresentationOptions({
      options: ['sound', 'badge', 'list', 'banner'],
    });

    const pushListener = Courier.shared.addPushNotificationListener({
      onPushNotificationClicked(push) {
        console.log(push);
        Alert.alert('👆 Push Notification Clicked', JSON.stringify(push));
      },
      onPushNotificationDelivered(push) {
        console.log(push);
        Alert.alert('📬 Push Notification Delivered', JSON.stringify(push));
      },
    });

    // Setup Inbox
    Courier.shared.setInboxPaginationLimit({ limit: 100 });

    return () => {
      pushListener.remove();
    };
  }, []);

  return <View className={'hidden'} />;
};
```

**And here is where I use the CourierInbox component**

```
type InboxData = {
  messages: InboxMessage[];
  unreadMessageCount: number;
  totalMessageCount: number;
  canPaginate: boolean;
};

const defaultState: InboxData = {
  messages: [],
  unreadMessageCount: 0,
  totalMessageCount: 0,
  canPaginate: false,
};

const CourierInbox = ({ setBadgeCount }: any) => {
  const [inboxData, setInboxData] = useState<InboxData>({ ...defaultState });

  useEffect(() => {
    const inboxListener = Courier.shared.addInboxListener({
      onError(error) {
        setInboxData({ ...defaultState });
        setBadgeCount(0);
      },
      onMessagesChanged(
        messages,
        unreadMessageCount,
        totalMessageCount,
        canPaginate,
      ) {
        setInboxData({
          messages,
          unreadMessageCount,
          totalMessageCount,
          canPaginate,
        });

        setBadgeCount(unreadMessageCount);
      },
    });

    return () => {
      inboxListener.remove();
    };
  }, []);

  console.log(inboxData);

  return (
    <Card
      className={'bg-white rounded-lg w-300 -ml-[300] h-[900]'}
      elevation={4}
    >
      <View className='h-full'>
        <CourierInboxView
          onClickInboxMessageAtIndex={(message, index) => {
            console.log(message);
            message.read
              ? Courier.shared.unreadMessage({ messageId: message.messageId })
              : Courier.shared.readMessage({ messageId: message.messageId });
          }}
          onClickInboxActionForMessageAtIndex={(action, message, index) => {
            console.log(action);
          }}
          style={{
            height: '100%',
          }}
        />
      </View>
    </Card>
  );
};

export const CourierInboxDD = () => {
  const [badgeCount, setBadgeCount] = useState<number>(0);

  return (
    <Dropdown
      renderMenu={({ closeMenu }) => {
        return <CourierInbox setBadgeCount={setBadgeCount} />;
      }}
    >
      <View pointerEvents={'none'} className={'relative'}>
        <Bell size={24} color={'black'} />
        <View
          className={
            'absolute top-0 right-0 bg-blue-950 rounded-full text-white'
          }
        >
          <Text>{badgeCount}</Text>
        </View>
      </View>
    </Dropdown>
  );
};
```

**Comment by colby-mchenry** [comment]
Another issue along with this, is that the onMessagesChanged function is not getting hit, even though I see the correct responses in the console log. I added a console log to the onMessagesChanged and no matter what it never calls.

**Comment by mikemilla** [comment]
@colby-mchenry I am currently looking into this bug, will report back shortly when we have a fix in place. Expect the fix early next week. Sorry if this is an inconvenience to you!

**Comment by mikemilla** [comment]
@colby-mchenry we just pushed an update to Inbox sockets. Please pull `2.3.0`. If you are still having issues, let me know. Will leave this issue open for a while longer.

**Comment by colby-mchenry** [comment]
@mikemilla We are working on some infrastructure that caused our GQL to go down. Once our stuff is up I will update, test, and report back.

**Comment by colby-mchenry** [comment]
@mikemilla I still seem to be getting the error after updating to 2.4.1. Now it renders "Bad response from the server"
<img width="301" alt="Screenshot 2024-02-19 at 4 56 35 PM" src="https://github.com/trycourier/courier-react-native/assets/140429921/f2494596-cab4-4ca5-866c-464975a35372">

And I'm getting the same exact web socket error in the console.

**Comment by colby-mchenry** [comment]
<img width="693" alt="Screenshot 2024-02-19 at 4 58 51 PM" src="https://github.com/trycourier/courier-react-native/assets/140429921/d1740d71-77f3-45bf-97ca-a2e214880cfe">
<img width="701" alt="Screenshot 2024-02-19 at 4 59 06 PM" src="https://github.com/trycourier/courier-react-native/assets/140429921/ba1dd808-d655-4774-8a1f-51afb77cdc8a">

**Comment by mikemilla** [comment]
Ok, Thanks @colby-mchenry looking into it. Thanks for the logs.

**Comment by mikemilla** [comment]
@colby-mchenry can you post your Courier.shared.signIn(...) function? You can redact the keys themselves.

This call is authenticated with the client key and requires you to configure the Courier Inbox provider in the Courier Studio here: https://app.courier.com/integrations/catalog/courier

Also, are you sending any custom data in your send request? Can you post an example of that too please if you are?

**Comment by colby-mchenry** [comment]
@mikemilla Finally getting back to this issue, it still seems to not be working. I also validated the users access token and I am passing a valid access token: 

```
 const { data, loading } = useQuery(GET_USER_BY_EMAIL, {
        fetchPolicy: 'network-only',
        skip: isLoading || !user?.email,
        variables: user?.email ? { email: user.email } : undefined,
        onCompleted: (data) => {
            // If we got a userId back we continue
            if (data.orgUserByEmail?.userId) {
                // Get access token for Courier
                getCourierAccessToken({
                    variables: {
                        userId: data.orgUserByEmail.userId,
                    },
                    onCompleted: (accessTokenData) => {
                        if (accessTokenData.courierAuth?.token && data.orgUserByEmail?.userId) {
                            // We log the user into Courier
                            console.log('Courier Access Token: ', accessTokenData.courierAuth?.token);
                            Courier.shared.signIn({
                                accessToken: accessTokenData.courierAuth?.token,
                                clientKey: Env.COURIER_PUBLIC_KEY,
                                userId: data.orgUserByEmail.userId,
                            }).then(() => {
                                // Once they are logged in to courier we route them
                                if (!data.orgUserByEmail?.termsAccepted) {
                                    router.navigate('/terms-of-service/');
                                } else {
                                    router.navigate('/home/');
                                }
                            });
                        }
                    }
                })
            }
        }
    });
    ```
    
    And in my log the accessToken prints:  Courier Access Token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6InVzZXJfaWQ6MjQ5MDY1ZjYtNTQ2......

**Comment by colby-mchenry** [comment]
I also have this enabled for both Production and Test


<img width="464" alt="Screenshot 2024-03-25 at 11 09 48 AM" src="https://github.com/trycourier/courier-react-native/assets/140429921/e0cc8b27-3f6a-4884-a668-8d9c1c4afc27">

**Comment by colby-mchenry** [comment]
@mikemilla I've also made sure I'm using the correct pk_test token, I've also made sure to decode the access token I use to put into Courier and I get this 

<img width="551" alt="Screenshot 2024-03-25 at 2 01 04 PM" src="https://github.com/trycourier/courier-react-native/assets/140429921/4e0539af-02d3-4241-8a94-b04dfb1a68d1">

**Comment by colby-mchenry** [comment]
Also now I'm getting 401 Unauthorized as a response

**Comment by mikemilla** [comment]
@colby-mchenry our mobile SDKs currently do not support JWT for Inbox unfortunately. We're working on fixes for this, but it will be a couple months until this rolls out.

**Comment by colby-mchenry** [comment]
@mikemilla  In the documentation it says an accessToken is required to go to production no?

https://github.com/trycourier/courier-react-native/blob/master/Docs/Authentication.md

**Comment by colby-mchenry** [comment]
@mikemilla after disabling the JWT setting it works! Thanks!

**Comment by mikemilla** [comment]
Yes @colby-mchenry, it's a bit confusing, but under the hood JWT is used for our REST endpoints and Client Key is used for our GraphQL endpoints.

It's weird, not ideal and was done as a work around.

Disabling JWT will solve it for now. Hope that is useful!

We are working on a fix internally that solves things much better, will update this thread when that is live.
