### ISSUE TITLE
com.courier.android.models.CourierException

### ISSUE THREAD

**Issue by treyshedrick** [trycourier/courier-react-native#17]
Receiving the following error logged after attempting to set up push notification 

`com.courier.android.models.CourierException: authentication_error: Unauthorized`
Is this an authentication error via Courier or Firebase?

**Comment by mikemilla** [comment]
The authentication is on the Courier side.

Take a look at this for more info: https://github.com/trycourier/courier-react-native/blob/master/Docs/PushNotifications.md#authenticate-and-test

TLDR:
1. You need to `signIn` to Courier before the SDK can sync push notification tokens.
2. Then, when you send a message to the device from Courier, you need to send to the user id you want to receive the push

If you do not have a user id, you can make one up.

If you are on production, you will likely need to perform a request to your backend to get a jwt for the user id before you sign in. More details here: https://github.com/trycourier/courier-react-native/blob/master/Docs/Authentication.md#going-to-production
