### ISSUE TITLE
getting 401 response from `GetMessages` query

### ISSUE THREAD

**Issue by will-short** [trycourier/courier-react-native#18]
I've confirmed the courier user is signed in and I'm delaying the render of CourierInboxView until it is like this:
 
 ```
    if (!Courier.shared.userId) {
        return null
    }

    return <CourierInboxView style={<styles>} />
```

 Here is my sign in debug logs:
 `LOG  COURIER Signing user in`
 `LOG  COURIER Access Token: <access token>`
 `LOG  COURIER Client Key: <client_key>`
 `LOG  COURIER User Id: <user_id>`
`LOG  COURIER Putting apn Token: <apn_token>`
`LOG  COURIER`
`New Courier API Request`
` LOG  COURIER Method: PUT`
``` LOG  COURIER Body: {
  "provider_key" : "apn",
  "device" : {
    "manufacturer" : "apple",
    "model" : "iPhone",
    "device_id" : "<device_id>",
    "app_id" : "<app_id>",
    "platform" : "ios"
  }
}
```
`LOG  COURIER Response Status: 204`
 `LOG  COURIER Response JSON: Empty`
 
 I'm using an auth_token with the following scopes: `user_id:${userId} inbox:read:messages inbox:write:events read:user-tokens write:user-tokens read:messages`
This is working for my web based inboxes

heres the response I'm getting for the `GetMessages` query 
``` 
LOG  COURIER Method: POST
 LOG  COURIER Body: {
  "query" : "query GetMessages(\n    $params: FilterParamsInput = { status: \"unread\" }\n    $limit: Int = 1\n    $after: String\n) {\n    count(params: $params)\n    messages(params: $params, limit: $limit, after: $after) {\n        nodes {\n            messageId\n        }\n    }\n}",
  "variables" : "{}"
}
 LOG  COURIER Response Status: 401
 LOG  COURIER Response JSON: {
  "message" : "Unauthorized",
  "type" : "authentication_error"
}
```

is there anything obvious I'm missing? 
 I'm pretty stumped since the same user on web has access to the inbox with the same method of fetching the auth_token

**Comment by will-short** [comment]
I was able to narrow it down a bit. it looks like I can get it to work if I disable  JWT Authentication on the client key.  Does this library not support the JWT authentication for inbox? @mikemilla

**Comment by mikemilla** [comment]
@will-short can you post your `Courier.shared.signIn(...)` function? You can redact the keys themselves.

This call is authenticated with the client key and requires you to configure the Courier Inbox provider in the Courier Studio here: https://app.courier.com/integrations/catalog/courier

**Comment by will-short** [comment]
yeah here is the function:
```
function useCourierSignIn() {
    const [hasSignedIn, setHasSignedIn] = useState(false)
    const { user } = useUserContext()
    const userId = user?.id

   // gets the signed auth token from our server
    const { data } = useGetCourierInboxAuthTokenQuery({
        skip: !userId,
    })

    const accessToken = data?.getCourierInboxAuthToken

    const isAuthenticatedAndNotSignedIn = userId && accessToken && !hasSignedIn

    if (isAuthenticatedAndNotSignedIn) {
        handleSignInAndPushPermission({
            accessToken,
            userId,
            onSuccess: setHasSignedIn,
        })
    }
}

async function handleSignInAndPushPermission({
    accessToken,
    userId,
    onSuccess,
}: {
    accessToken: string
    userId: string
    onSuccess: Dispatch<SetStateAction<boolean>> | (() => void)
}) {
    try {
        await Courier.shared.signIn({
            accessToken: accessToken,
            clientKey: getCourierClientKey() // just a env var with our client key,
            userId,
        })

        await Courier.shared.requestNotificationPermission()
        onSuccess(true)
    } catch (error) {
        console.log('ERROR', error)
    }
}
```

**Comment by will-short** [comment]
had some time to dig a bit more into this.  I looked into how web is authorizing its graphql requests vs how the mobile libraries are doing it. 

I saw that when the client is created for web it sets the generated auth token that is generated here: 
https://www.courier.com/docs/platform/inbox/authentication/#json-web-tokens

heres a snippet I found from for how the web is settings the headers in [createCourierClient](https://github.com/trycourier/courier-react/blob/9b2d4661f74e70fc7e2d54b15da312b520f615a4/packages/client-graphql/src/client.ts):
```js
    headers = {
      authorization: `Bearer ${jwtParams.authorization}`,
      "x-courier-client-key": jwtParams.clientKey,
    } as CourierJWTHeaders;

```
and that is sent along with the getMessages query `"authorization": "Bearer <token>`

looking at the mobile projects (I am not super familiar with swift so please correct me if im wrong):
it only adds clientKey and userId for the graphql queries as seen in this [file](https://github.com/trycourier/courier-ios/blob/cd1eb6befe7ed0ec99262bda7de22a7225039c80/Sources/Courier_iOS/Repositories/Repository.swift): 

```swift
request.addValue(clientKey, forHTTPHeaderField: "x-courier-client-key")
request.addValue(userId, forHTTPHeaderField: "x-courier-user-id")
```

and in android its the same [here](https://github.com/trycourier/courier-android/blob/e46307eabccfd956ba7f9c0a7e6fa23cdc9f44de/android/src/main/java/com/courier/android/repositories/InboxRepository.kt):
```kotlin
        val request = Request.Builder()
            .url(inboxGraphQL)
            .addHeader("x-courier-client-key", clientKey)
            .addHeader("x-courier-user-id", userId)
            .post(query.toRequestBody())
            .build()
```

the way I understand it is to be able to turn on this toggle for the courier client key:
<img width="416" alt="Screenshot 2024-03-05 at 10 58 47 AM" src="https://github.com/trycourier/courier-react-native/assets/16979047/711725ba-098d-4ea9-9138-9b64fa1355de">

we have to pass the auth token in the headers of every request. 

So if I'm understanding it all correctly we are unable to enable JWT auth if we want to use Mobile Inbox. 

Do you know if there's a roadmap to being able to enable that?

**Comment by mikemilla** [comment]
@will-short for iOS and Android Inbox you do not need to do anything special. Simply add the client key at `signIn`, which you have setup.

I'm thinking there may be a race condition some where or you are calling `signIn` too often.

Please double check all of your credentials, or book a call with me and we can work through this: https://cal.com/mikemilla

**Comment by will-short** [comment]
JWT authentication is not available for inbox on this library at this time. For anyone else running into this: you need to disable JWT authentication on the courier inbox integration, otherwise you'll get a unauthenticated error when trying to query messages.  Thanks @mikemilla for hopping on a call and explaining whats going on.
