### ISSUE TITLE
Getting 401 Unauthorised error for Courier Inbox

### ISSUE THREAD

**Issue by tb-nishant** [trycourier/courier-react-native#19]
Facing a very similar issue to [this one](https://github.com/trycourier/courier-react-native/issues/18), but the resolution posted there didn't help me.

I'm trying to migrate from `@trycourier/react-hooks` to use this react-native SDK. User seems to be signing in correctly, but when I try to use `CourierInboxView` (or `Courier.shared.addInboxListener`) I'm getting a 401 error. 

<img width="1032" alt="Screenshot 2024-03-18 at 10 59 44 PM" src="https://github.com/trycourier/courier-react-native/assets/124140797/5deac674-c562-4229-b9bc-d7689eea21bb">

### Authentication
Using below code for signing the user in and setting Expo token. Currently I'm in development mode and passing `authToken` here instead of `accessToken`, according to [the docs](https://github.com/trycourier/courier-react-native/blob/master/Docs/Authentication.md#usage).

```
await Courier.shared.signIn({
  accessToken: $AUTH_TOKEN,
  clientKey: $CLIENT_KEY,
  userId: `${user}`,
});
await Courier.shared.setTokenForProvider({
  provider: CourierPushProvider.EXPO,
  token: expoToken,
});
```

In [Courier integration](https://app.courier.com/integrations/catalog/courier) settings, the `Enable JWT Authentication (Recommended)` setting is disabled, and `Enable HMAC Authentication (Legacy)` is enabled as suggested in the [linked issue](https://github.com/trycourier/courier-react-native/issues/18).

Thanks in advance!

**Comment by tb-nishant** [comment]
`react-native info` output:
```
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 503.19 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
  ```

**Comment by mikemilla** [comment]
Courier Inbox for Mobile only works with client key authorization at the moment @tb-nishant. There will be changes to this in the future, but those will come in a later release.

To fix this, you must have a valid client key and these settings in your Courier Inbox Integration.

<img width="450" alt="Screenshot 2024-03-21 at 2 00 01 PM" src="https://github.com/trycourier/courier-react-native/assets/6370613/427ce737-2e87-46f7-b0f6-f47af7769171">

If you have questions ping me here or book a call. https://cal.com/mikemilla

**Comment by tb-nishant** [comment]
Thanks @mikemilla. We're using HMAC auth in production already, so turning it off is not an option. Looks like we must stick to `@trycourier/react` for the time being 😢.
Do you have an ETA for this to feature?

**Comment by mikemilla** [comment]
@tb-nishant we're going to do some large scale updates to the requests in our SDKs. No set date on this yet. Likely a couple months out unfortunately.

**Comment by mikemilla** [comment]
@tb-nishant JWTs are now supported in version 3.0.0 which is live now: https://github.com/trycourier/courier-react-native/releases/tag/3.0.0

Simply use `signIn` like this:

```
await Courier.shared.signIn({
  accessToken: YOUR_JWT,
  userId: YOUR_USER_ID,
});
```
