### ISSUE TITLE
Issues with Expo Support for Push Notifications

### ISSUE THREAD

**Issue by divquan** [trycourier/courier-react-native#21]
I’m following up on issue [#10](https://github.com/trycourier/courier-react-native/issues/10) regarding Expo support. The proposed solution for manually syncing Firebase Cloud Messaging tokens doesn’t seem to be working in my project.

I’m building a mobile app with Expo and need users to subscribe to push notifications through a button. Could you provide any updates on Expo support? An integrated solution would be really helpful.

Thanks!

**Comment by mikemilla** [comment]
@divquan we do support setting any token in the SDK now. Here are the related docs:

With Sign In (this is the easiest way)
https://github.com/trycourier/courier-react-native/blob/master/Docs/Authentication.md
https://github.com/trycourier/courier-react-native/blob/master/Docs/PushNotifications.md#manual-token-syncing

```javascript
await Courier.shared.signIn({
  ...
});

await Courier.shared.setTokenForProvider({
  provider: CourierPushProvider.EXPO,
  token: 'example_token'
});

const tokenForProvider = await Courier.shared.getTokenForProvider({
  provider: CourierPushProvider.EXPO
});
```

Or with this (the more technical way)
https://github.com/trycourier/courier-react-native/blob/master/Docs/Client.md#token-management-apis

```javascript
const client = new CourierClient({
  ...
});

await client.tokens.putUserToken({
  token: "...",
  provider: "expo",
)

await client.tokens.deleteUserToken({
  token: "..."
})
```

Both of these will put your tokens into Courier, then you can send messages to them.

I'm around if you have any other questions. I'll be watching this thread.

**Comment by mikemilla** [comment]
Closing this for now. @divquan Feel free to ping me here if you have any other questions.
